### ISSUE TITLE
Project_Review-able-spoon-1296

### ISSUE THREAD

**Issue by vivekanand-pandey-maersk** [prashant174/Live-Your-Text#21]
1. Is this a Project Name(Unit5) 
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/78374079/219883463-a90d0244-2fe1-4578-8971-7490ce65d46e.png">
what someone understand if come to this GitHub Page
2. Documentation is also not Proper
3. What is this Project, Project giving 
socket connection failed, try again later.
error on the begging it self 
4. I think this Project is not yet completed
5. if this is the project then it's not good for any things wast of time
6. Inline css used in that code that is also not good
7. Only Two Component in this Project and Most Of The Code are commented
8. No Validation 
9. Overall Project is wast of Time
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/78374079/219883900-84f1d311-2b30-423e-b308-9b19229d86ca.png">

**Comment by prashant174** [comment]
This project is not complete yet I'm working on it
